language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  - "pypy"
  - "pypy3"
allow_failures:
  - python: 3.2
  - python: "nightly"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; fi
install:
  - pip install -e .
  - pip install -r requirements_test.txt
script:
  - python setup.py test
